# Configuration with perfect link and NV qdevice with noise
qdevice_cfq: &qdevice_cfg
    # number of qubits per NV
    num_qubits: 6

    # initialization error of the electron spin
    electron_init_depolar_prob: 0

    # error of the single-qubit gate
    electron_single_qubit_depolar_prob: 0

    # measurement errors (prob_error_X is the probability that outcome X is flipped to 1 - X)
    # Chance of 0 being measured as 1
    prob_error_0: 0
    # Chance of 1 being measured as 0
    prob_error_1: 0

    # initialization error of the carbon nuclear spin
    carbon_init_depolar_prob: 0

    # error of the Z-rotation gate on the carbon nuclear spin
    carbon_z_rot_depolar_prob: 0

    # error of the native NV two-qubit gate
    ec_gate_depolar_prob: 0

    # coherence times
    electron_T1: 1_000_000_000_000_000
    electron_T2: 1_000_000_000_000_000
    carbon_T1: 0
    carbon_T2: 0

    # gate execution times
    carbon_init: 0
    carbon_rot_x: 0
    carbon_rot_y: 0
    carbon_rot_z: 0
    electron_init: 0
    electron_rot_x: 0
    electron_rot_y: 0
    electron_rot_z: 0
    ec_controlled_dir_x: 0
    ec_controlled_dir_y: 0
    measure: 0

# 3 node network, noise
stacks:
  - name: Sender
    qdevice_typ: nv
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Receiver0
    qdevice_typ: nv
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Receiver1
    qdevice_typ: nv
    qdevice_cfg:
      <<: *qdevice_cfg

link_cfg: &link_cfg
    prob_success: 0.001
    fidelity: 1.0
    t_cycle: 1e3

links:
  - stack1: Sender
    stack2: Receiver0
    typ: depolarise
    cfg:
      <<: *link_cfg

  - stack1: Sender
    stack2: Receiver1
    typ: depolarise
    cfg:
      <<: *link_cfg

  - stack1: Receiver0
    stack2: Receiver1
    typ: perfect



clinks:
  - stack1: Sender
    stack2: Receiver0
    typ: instant

  - stack1: Sender
    stack2: Receiver1
    typ: instant

  - stack1: Receiver0
    stack2: Receiver1
    typ: instant

